image: public.ecr.aws/docker/library/python:3.8

stages:
  - test
  - profile
  - pypi

run_tests:
  stage: test
  resource_group: ssh-helper-tests
  script:
    # Run tests
    - bash run_tests.sh
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: tests/pytest_report.xml
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml
    paths:
      - dist/
      - .pypirc
      - src_diff/
      - pip_freeze/
      - tests/pytest_report.xml
      - tests/pytest_report.html
      - tests/htmlcov/
      - tests/coverage.xml
      - tests/.coverage
      - tests/.pymon
      - tests/output/
      - bandit.txt
      - flake8.txt

profile_tests:
  stage: profile
  when: manual
  dependencies:
    - run_tests
  resource_group: ssh-helper-tests
  rules:
    - if: $SKIP_PROFILE_TESTS == "false"
  script:
    - bash profile_tests.sh
  artifacts:
    when: always
    paths:
      - tests/prof/

publish_testpypi:
  stage: pypi
  when: manual
  dependencies:
    - run_tests
  script:
    - ls dist/
    - sed -e "s~__password__~$PyPI_Test_API_token~" .pypirc > $HOME/.pypirc
    - pip install -U twine
    - python -m twine upload --verbose --repository testpypi dist/*

publish_prodpypi:
  stage: pypi
  when: manual
  dependencies:
    - run_tests
  rules:
    - if: $PyPI_API_token != null
  script:
    - ls dist/
    - sed -e "s~__password__~$PyPI_API_token~" .pypirc > $HOME/.pypirc
    - pip install -U twine
    - python -m twine upload --verbose --repository pypi dist/*
